default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: ska_portfolio_development

test:
  <<: *default
  database: ska_portfolio_test


production:
  <<: *default
  database: ska_portfolio_production
  
