# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f5d7891c7c5459d29716580fa020a33e7298baa7de160b5c71ea4ff790936db87dabaad43c0dc5f2c058debbf6875c86448299f18c6e2c8f322d039cb39131

test:
  secret_key_base: e327fddbbf15dd913ecf33bc3565e902a19087424e235523c668b3fb5a9e06dd6da5243447693692f5c628fa791573737339dc74e5fa590dc747e2911e29dde5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
